### ISSUE TITLE
Extend the documentation for other languages

### ISSUE THREAD

**Issue by UltraBlackLinux** [JsMacros/JsMacros#102]
Hey there,
I was hoping to use this mod with the Lua extension to get back into some fun experimenting like back with the Macro/Keybind mod, but I'm facing a problem: The documentation is not concise enough for me to use.

This for example: https://github.com/JsMacros/JsMacros/wiki/JsMacros-Functions#onstring-biconsumerstring-mapstring-object-123

What is `String, Map<String, Object>`? What does the string do, and what the object? Since Lua has practically no types it could just do anything with that. What does the IEventlistener contain in general?
The event name is also a string - Does capitalization matter?

Could you give me an example, e.g. printing the server IP when connecting to a server? I think that would help a ton.

Thanks!

**Comment by shenjackyuanjie** [comment]
I think you can check the https://jsmacros.wagyourtail.xyz/?/general.html first
this web page is more readable than the wiki

**Comment by UltraBlackLinux** [comment]
Right I forgot  to close this issue. I noticed wiki deprecation warning too late
