### ISSUE TITLE
Can't add more than one instance of each type of RenderElement3D to a Draw3D

### ISSUE THREAD

**Issue by Dit05** [JsMacros/JsMacros#110]
I highly suspect that https://github.com/JsMacros/JsMacros/commit/0933229e3a8ae76d2dcfea6fae64d173799ca70a caused this, with its wacky RenderElement3D.compareTo implementation.
It consists of comparing the class names of the involved objects, which seems very incorrect, as compareTo is meant to compare the actual values of instances.

Draw3D stores added RenderElement3D in a TreeSet:
https://github.com/JsMacros/JsMacros/blob/c44892deb667e2069031e035cb0abdb96fbadc73/src/main/java/xyz/wagyourtail/jsmacros/client/api/classes/render/Draw3D.java#L30C29-L30C29

Since TreeSet is a Set, it either contains or doesn't contain an element, and I'm pretty sure that TreeSet is a binary tree, so the way it determines if an item is already present is by invoking compareTo. If that reports equality, it doesn't add the item. And because all RenderElement3Ds of the same type compareTo each other as equals, this must be the cause of the issue.

Now I am no Java programmer, so this is just my best guess at the problem and I can't test any fixes. I hope this helps resolve the issue, though.

For completeness's sake, here's a script that's affected by this:
```
const d3d = Hud.createDraw3D()

d3d.register();

const ticklistener = JsMacros.on("Tick", JavaWrapper.methodToJava(() => {
    d3d.clear();
    
    let me = Player?.getPlayer();
    
    if(!me) {
        return;
    }
    
    const pos = me.getPos();
    
    let entities = World.getEntities(32);
    
    
    for(let i = 0; i < entities.size(); i++) {
        let ent = entities[i];
        
        let entPos = ent.getPos();

        d3d.addPoint(entPos, 0.1, 0xff0000);
        d3d.addLine(entPos.getX(), entPos.getY(), entPos.getZ(), 0, 0, 0, 0x00ff00, false);
        
    }
    
    Chat.actionbar(d3d.getBoxes().size()); // never more than 1

}));



// this fires when the service is stopped
event.stopListener = JavaWrapper.methodToJava(() => {
    d3d.unregister();
    JsMacros.off(ticklistener);
});
```

**Comment by wagyourtail** [comment]
> I highly suspect that https://github.com/JsMacros/JsMacros/commit/0933229e3a8ae76d2dcfea6fae64d173799ca70a caused this
that shouldn't be making the hash codes equal... afaik that's only used for sorting

**Comment by wagyourtail** [comment]
fixed in https://github.com/JsMacros/JsMacros/commit/698b70f0072d702ba24d152c031ff73fdf6b083c
