### ISSUE TITLE
Creating file or editing a macro file causes crash because "ex" is null

### ISSUE THREAD

**Issue by kmaxii** [JsMacros/JsMacros#115]
The game crashed whilst mousereleased event handler
Error: java.lang.NullPointerException: Cannot invoke "xyz.wagyourtail.jsmacros.core.extensions.Extension.getLanguage(xyz.wagyourtail.jsmacros.core.Core)" because "ex" is null. For full crash, check this out: https://hastebin.com/share/dudahekiwe.makefile

**Comment by kzvi** [comment]
Update to jsmacros 1.8.5
