### ISSUE TITLE
Services stop working on profile switch

### ISSUE THREAD

**Issue by thojo0** [JsMacros/JsMacros#118]
Services stop working on a profile switch.

They don't stop in the JsMacros Screen, but a lot of functionality doesn't work anymore.
Mainly any listener.

After stoping and starting every Service they work again like intended.

**Comment by wagyourtail** [comment]
fixed in https://github.com/JsMacros/JsMacros/commit/250567d8698dedd1bdc2e557eb19361c8b6233a0
