### ISSUE TITLE
[1.20.1] Player.openInventory().getHeld() only shows air.

### ISSUE THREAD

**Issue by arden-arteles** [JsMacros/JsMacros#158]
Whenever I attempt to get my held item, it only shows that I have air. I have checked this using chat logging.

My macro:
```js
const inventory = Player.openInventory();

Chat.log(inventory.getHeld());
```
(abbreviated for testing purposes, this still shows the bug. This is attached to ItemPickup.)

This should be giving something like a fishing rod, but it is not.

**Comment by wagyourtail** [comment]
Get held returns the held (by the mouse) item. Meaning when you click a stack. That one.

For that, you want `Player.getPlayer().getMainHand()`
https://jsmacros.wagyourtail.xyz/?/1.9.2/xyz/wagyourtail/jsmacros/client/api/helpers/world/entity/LivingEntityHelper.html#getMainHand-
