### ISSUE TITLE
Network Protocol Error

### ISSUE THREAD

**Issue by jurohn** [JsMacros/JsMacros#159]
Paper server 1.20.6

Using:
Fabric launcher 
fabric-api-0.99.0+1.20.6
jsmacros-1.20.5-1.9.2-fabric

Reproduce:
On a 1.20.6 supported server, place a lectern, on top place a book and quil and right click it. It will kick you from the server.

No events enabled
No macro's enabled

![image](https://github.com/JsMacros/JsMacros/assets/137065095/f5fbbe87-3f84-4f9a-9c7d-9d202421c9fc)

**Comment by wagyourtail** [comment]
logs?
