### ISSUE TITLE
 ScoreboardObjectiveHelper.getPlayerScores() returns empty string for player names if not actual player

### ISSUE THREAD

**Issue by LeaPhant** [JsMacros/JsMacros#48]
Most servers utilize scoreboards with fake players to show info, it seems like [getPlayerScores()](https://jsmacros.wagyourtail.xyz/?/1.6.4/xyz/wagyourtail/jsmacros/client/api/helpers/ScoreboardObjectiveHelper.html#getPlayerScores-)  just returns empty strings for the names in these cases.

Example code:
```JS
const scoreboard = World.getScoreboards().getCurrentScoreboard();
Chat.log(scoreboard.getPlayerScores());
```

Output with a scoreboard made via 
`/scoreboard objectives add Deaths deathCount` and `/scoreboard objectives setdisplay sidebar Deaths`:
```
{LeaPhant=1}
```

Output upon joining hypixel.net:
```
{=1, =2, =3, =4, =5, =6, =7, =8, =9, =10, =11}
```
The actual scoreboard:

![image](https://user-images.githubusercontent.com/14080165/156834713-2eb1a670-071e-41a5-9be2-42739d4f4b7b.png)

**Comment by wagyourtail** [comment]
looking at console. player names are `[§g, §h, §i, §j, §p, §q, §s, §t, §u, §v, §w, §x, §y, §z, §!]`
and the data is stored in the team names. I will make the data easier to reach
