### ISSUE TITLE
Draw2D setOnInit doesn't work properly

### ISSUE THREAD

**Issue by aMelonRind** [JsMacros/JsMacros#63]
[latest.log](https://github.com/JsMacros/JsMacros/files/9194965/latest.log)
check at the end of latest.log for stacktrace

my test.js content:
  const d2d = Hud.createDraw2D()
  d2d.setOnInit(JavaWrapper.methodToJava(() => {}))
  d2d.register()

**Comment by mart3323** [comment]
Possibly the same issue as https://discord.com/channels/732004268948586545/732004614005719082/992823284657815582, in case that helps track it down

**Comment by wagyourtail** [comment]
> Value.isHostObject()

you appear to be using a beta version of jsmacros `1.8.0` (built locally?), this was fixed in https://github.com/JsMacros/JsMacros/commit/41dfee67ddd923eeaf5cfe989067afa06da2562a
