### ISSUE TITLE
add quick craft button

### ISSUE THREAD

**Issue by tympanicblock61** [JsMacros/JsMacros#64]
can you add quick craft buttons like .quickCraftPress(button) button being the button like stick or enchanting table

**Comment by aMelonRind** [comment]
https://jsmacros.wagyourtail.xyz/?/1.8.0/xyz/wagyourtail/jsmacros/client/api/classes/Inventory.html#getCraftableRecipes-
there's a craft() method

**Comment by tympanicblock61** [comment]
ik i mean these buttons 
![image](https://user-images.githubusercontent.com/99092380/181937480-a9962c38-145e-4f09-8422-e3a71e9badee.png)
