### ISSUE TITLE
EventDamage always return "generic" as Source

### ISSUE THREAD

**Issue by R4z0rX** [JsMacros/JsMacros#67]
Hi!

I'm trying to do something when a player falls to the void, and I need to use the [Damage event](https://jsmacros.wagyourtail.xyz/?%2F1.8.0%2Fxyz%2Fwagyourtail%2Fjsmacros%2Fclient%2Fapi%2Fevent%2Fimpl%2FEventDamage.html) with the specific Source "OutOfWorld"...

`if (event.source == 'outOfWorld')`

...but I always get "generic" as source, no matter the real source (fall damage, attacked by a zombie, etc.)
So, looking at your code I discover you have this hardcoded here:

https://github.com/JsMacros/JsMacros/blob/1bc591dc2c617f34d9f42992e99c3c6dc99ba296/common/src/main/java/xyz/wagyourtail/jsmacros/client/mixins/events/MixinLivingEntity.java#L43

I'm not so good a Java programming. Could you fix this?
Thanks in advance.

**Comment by wagyourtail** [comment]
can't fix, server doesn't give that info, the only reason that's there is because older versions of jsmacros

**Comment by R4z0rX** [comment]
Oh, I see. Well, don't worry, I took a different approach looking at the speed the Y coordinate decrease, and if it's below -127 I trigger my custom event.
So, thanks anyway. 😀
