### ISSUE TITLE
Global Variables Issues

### ISSUE THREAD

**Issue by Cyranos** [JsMacros/JsMacros#69]
Global Variables do not update till you restart your MC Instance

**Comment by wagyourtail** [comment]
what?

**Comment by Cyranos** [comment]
I have a global variable inside of the index.js file called cooldown, if I have it set too 500 when I click play to launch my minecraft modpack, then I load into a world but then feel like I want to change it too 250 or whatever & save it, whatever is use that global variable would still see the original 500 not 250

**Comment by wagyourtail** [comment]
that's a problem with how you're using it. if you retrieve the variable after change, it'll be changed.

test script:
```js
GlobalVars.putInt("test", 500);
Chat.log(GlobalVars.getInt("test"));
GlobalVars.putInt("test", 250);
Chat.log(GlobalVars.getInt("test"));
```
