### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by CoolestGuy94** [JsMacros/JsMacros#70]
I can see, I can read... I can't hear??
Adding sounds to JsMacros would be good!

**Comment by Sp3rick** [comment]
yeh something like JSMacros.playSound(SoundName) or also JSMacros.playSound("./MajorTyler.mp3")

**Comment by Sp3rick** [comment]
> I can see, I can read... I can't hear?? Adding sounds to JsMacros would be good!

mhh just found that it already exist, check World.playSound in the library: https://jsmacros.wagyourtail.xyz/?/1.8.0/xyz/wagyourtail/jsmacros/client/api/library/impl/FWorld.html

**Comment by wagyourtail** [comment]
there's also already the sound event
